version: '3'

networks:
  gnet:
    driver: bridge

services:
  broker-service:
    container_name: broker-apps
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - gnet